
# See http://www.appveyor.com/docs/appveyor-yml for many more options
# Fron https://github.com/RamblingCookieMonster/PSStackExchange/blob/master/appveyor.yml

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

test_script:
# Test with native PS version
  - ps: . .\build.ps1